import { useState, useEffect } from "react";
import { Link } from "react-router-dom";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";

const SECTIONS = [
  {
    num: "1",
    title: "Roles and responsibility",
    content: `Legora's Services are offered to companies and/or other legal entities for professional use (our "Subscribers"). Our Subscriber agreements govern the delivery and use of the Services ("Subscriber Agreements").\n\nThis Privacy Policy applies when Legora is the data controller responsible for processing personal data. It does not apply to any input submitted to, output generated by, or documents uploaded to our Services ("Content"). We process Content as a data processor on behalf of our Subscribers (the data controllers), and our processing of Content is governed by the relevant Subscriber Agreement. Any queries related to data that can be used to identify you ("personal data") included in Content should be directed to our Subscribers. If we receive any rights requests concerning instances where we act as data processor, we will forward them to the relevant Subscriber.\n\nLegora may maintain links to other websites and other websites may maintain links to the Online Services. This Privacy Policy only applies to legora.com, leya.law, app.legora.com and app.leya.law, and not to other websites accessible from Legora or websites that you use to access Legora.`,
  },
  {
    num: "2",
    title: "What information does Legora collect",
    subsections: [
      {
        num: "2.1",
        title: "Information you provide to us",
        content: `We collect personal data provided to us if you create an account to use our Services or communicate with us as follows:\n\n**User account information**: We require everyone with access to our Services to have an account with us. When you or your employer creates a Legora account for you, we collect personal data including your name, email address, role, language preferences and account credentials.\n\n**Communication information**: When you contact us for customer support, feedback, or inquiries, we collect your name, email address, phone number, and any other information you provide us with to assist you or resolve your issue. Legora may monitor and record phone conversations or email communications between you and Legora employees for training and quality assurance purposes.\n\n**Social media information**: We have accounts on social media sites like LinkedIn, YouTube and X ("Social Media"). When you interact with our Social Media, we will collect personal data that you elect to provide to us, such as your contact details.\n\n**Survey and contest information**: We may provide you the opportunity to participate in surveys on our Site, to measure customer satisfaction. Participation in these surveys or contests is completely voluntary.\n\n**Testimonial and review information**: We may display personal testimonials or reviews from satisfied users if you have consented to it. If you wish to update or delete your testimonial or review, you can contact us.`,
      },
      {
        num: "2.2",
        title: "Information we automatically collect",
        content: `When you visit, use, and interact with our Services, we will collect certain information about your visit, use, or interactions ("Technical Information") indirectly, including through automated means from your computer or device, including the following:\n\n**Log data**: Whenever you visit the Online Services, your browser will automatically send us your IP address, browser type and settings, the date and time of your request, and how you interacted with the Online Services.\n\n**Device information**: We will automatically collect information about the device you are using to access the Online Services, including name of the device, operating system, browser, referring/exit pages, date/time stamps, and clickstream data.\n\n**Usage data**: We will automatically collect information about your use of our Services, including the features you use, actions you take, your time zone, location, and types and volumes of queries you submit.\n\n**Cookies**: Legora uses Essential Cookies, Performance and Analytics Cookies (including Google Analytics), and Functional Cookies. You can turn off all cookies via your browser settings.`,
        bullets: [
          { label: "Essential Cookies", text: "these are essential in order to enable you to move around the website and use its features, such as accessing secure areas of the website." },
          { label: "Performance and Analytics Cookies", text: "these include Google Analytics and they keep track of the pages that you visit on our Site and the content you access, so we can determine which content is most popular and improve the performance of our website." },
          { label: "Functional Cookies", text: "these cookies remember the choices you make, such as language options or the region you are in. They are deleted automatically when you close your browser or the session expires." },
        ],
      },
      {
        num: "2.3",
        title: "Information collected from third parties",
        content: `We may collect information about you from third parties, such as security partners, marketing vendors and event organizers. Our Subscribers may give us information about you, such as your contact details, in order to facilitate us providing our Services. We may combine this information with information we collect from you and use it as described in this Privacy Policy.`,
      },
      {
        num: "2.4",
        title: "Publicly available information",
        content: `We provide access to publicly available information (for example, judgments and decisions) within our Services. Some of this information may relate to individuals and can, in some jurisdictions, be considered personal data. Personal data included in publicly available information is only processed so that our Services can provide more accurate and relevant responses. It is not provided to intentionally identify individuals.\n\nLegora also collects publicly available information about Subscribers and prospects, including name, email address, phone number and other contact details.`,
      },
      {
        num: "2.5",
        title: "Aggregated information",
        content: `Legora may aggregate personal data and use the aggregated information to analyze the effectiveness of our Services, improve and add features to our Services. In addition, from time to time, we may analyze the general behavior and characteristics of users of our Services and share aggregated information like general user statistics with third parties, publish such aggregated information or make such aggregated information generally available.`,
      },
    ],
  },
  {
    num: "3",
    title: "How we use your personal data",
    content: `Legora may use your personal data for the following purposes:`,
    list: [
      "to provide, administer, maintain, and/or improve our Services;",
      "to provide you with support services, resolve issues or reply to your queries;",
      "to manage and remember your preferences and customize the Services;",
      "to communicate with you, including to send you information or marketing about our Services and events;",
      "to analyze and study the effectiveness of our Services and to develop new features and services;",
      "to verify your identity, prevent fraud, criminal activity and to ensure the security of our IT systems, architecture, and networks;",
      "to prevent misuse of the Services and enforce our legal terms;",
      "to comply with legal obligations and legal processes, and;",
      "to protect Legora's rights, privacy, safety, or property, and/or that of our affiliates, you, or other third parties.",
    ],
    tableNote: "The following disclosures provide additional information about the categories of Personal Information we collect, the type of data, how we use each category. These disclosures do not limit our ability to use or disclose information as described above.",
    table: [
      { purpose: "To manage our customer relationship with you and/or your employer in accordance with our agreements.", data: "User account information, Communication information, Log data, Device information, Usage data.", basis: "Necessary for Legora to perform a contract with you and/or your employer (Article 6(1)(b) GDPR).", retention: "When the relevant contracts terminate." },
      { purpose: "To perform end user satisfaction surveys, conduct market research and ask for reviews.", data: "Survey and contest information, Testimonial and review information, Technical Information.", basis: "Balancing of interests (Article 6(1)(f) GDPR).", retention: "When the contract between us terminates." },
      { purpose: "To ensure network and information security in Legora's Services.", data: "User account information, Technical Information.", basis: "Balancing of interests (Article 6(1)(f) GDPR).", retention: "For as long as you are using the Services." },
      { purpose: "To perform data analysis for development and improving our Services.", data: "User account information, Technical Information.", basis: "Balancing of interests (Article 6(1)(f) GDPR).", retention: "For as long as you are using the Services." },
      { purpose: "To calculate usage costs in relation to suppliers and Subscribers.", data: "Usage data.", basis: "Necessary to perform a contract (Article 6(1)(b) GDPR) and balancing of interests (Article 6(1)(f) GDPR).", retention: "Up to 6 months after using a Service or longer if required." },
      { purpose: "To check and verify your identity.", data: "User account information, Technical Information.", basis: "Necessary for Legora to perform a contract (Article 6(1)(b) GDPR).", retention: "As long as you use the Services." },
      { purpose: "To provide you with direct marketing and marketing surveys.", data: "Communication information, Social media information, Technical Information.", basis: "Based on your consent (Article 6(1)(a) GDPR).", retention: "Until you withdraw consent or opt-out." },
      { purpose: "To protect Legora from legal claims and safeguard Legora's legal rights.", data: "All types mentioned in Section 2.", basis: "Balancing of interests (Article 6(1)(f) GDPR).", retention: "For the entire period during which Legora must retain the information." },
    ],
  },
  {
    num: "4",
    title: "With whom we share your personal data",
    content: `In certain circumstances, we may share your Personal Information with third parties without further notice to you, unless legally required, including without limitation in the situations below:`,
    boldList: [
      { term: "Affiliates", text: "Legora may share your personal data with other entities within the Legora corporate group (our 'affiliates'). Legora's affiliates will only use the personal data we share with them in a manner consistent with this Privacy Policy." },
      { term: "Vendors and Service Providers", text: "To assist us in meeting business operations needs and to perform certain services and functions, we may share your personal data with vendors and service providers, including providers of hosting services, cloud service providers, and other information technology services providers." },
      { term: "Third-party Websites and Services", text: "Our Services may contain links to other websites not operated or controlled by Legora, including social media services ('third-party sites'). The information that you share with third-party sites will be governed by the specific privacy policies and terms of service of the third-party sites and not by this Privacy Policy." },
      { term: "Other users", text: "When you are using the collaboration features within Legora, certain actions you take may be visible to other users of our services." },
      { term: "Plug-Ins", text: "When you are using third party applications and choose to connect your Legora account with such external third-party applications the providers of those services or products may receive information about you from Legora or others." },
      { term: "Business changes", text: "If we are involved in strategic transactions, (such as sale, merger, reorganizations, liquidation, or transition of service to another provider), your personal data and other information may be shared in the diligence process with counterparties." },
      { term: "Legal Requirements", text: "Legora may also share your personal data if required to do so by law or in the good faith belief that such action is necessary to comply with a legal obligation, protect and defend our rights or property, prevent fraud, or protect against legal liability." },
    ],
  },
  {
    num: "5",
    title: "International transfers",
    content: `Legora always strives to process your personal data as close to you as possible. By using our Online Services however, you understand and acknowledge that your personal information will be transferred from your location to our facilities and servers in the EU/EEA.\n\nIn certain situations, such as when we share your information within the Legora corporate group or with a supplier or subcontractor, your personal data may be transferred outside EU/EEA. Legora always ensures that the same high level of protection applies to your personal data according to the relevant data protection laws, even when the data is internationally transferred.\n\nSuch appropriate safeguards include, but are not limited to:`,
    italicList: [
      { term: "Adequacy decisions", text: "If the relevant authority (e.g. the EU Commission) has decided that the country to which your personal data are transferred has an adequate level of protection." },
      { term: "Standard Contractual Clauses", text: "The relevant authority's standard clauses have been entered into between Legora and the recipient of the personal data." },
      { term: "Derogation", text: "In limited circumstances, we may rely on an exception under the applicable data protection laws, such as relying on your explicit consent to that transfer." },
      { term: "Data Privacy Framework", text: "If the transfer is covered by a relevant data privacy framework, such as the EU-US Data Privacy Framework, administered by the US Department of Commerce." },
    ],
  },
  {
    num: "6",
    title: "What are your rights",
    content: `You have several rights under the applicable data protection laws (including the GDPR) related to your control over your personal data and to receive information directly from us on how we process personal data about you. In the following you can read about your rights.`,
    boldList: [
      { term: "Right to information and access", text: "You have the right to be informed of how we process your personal data. You can request information regarding whether we are processing your personal data and ask to receive a copy of your personal data ('data extract')." },
      { term: "Right to rectification", text: "If you believe that your personal data is inaccurate or incomplete, you have the right to ask for it to be corrected or completed." },
      { term: "Right to restriction", text: "If you believe that your personal data is inaccurate, that our processing is unlawful or that we do not need the information for a specific purpose, you have the right to request that we restrict the processing of such personal data." },
      { term: "Right to object", text: "You have the right to object to the processing of your personal data which is based on our legitimate interest (Article 6(1)(f) GDPR), by referencing your personal circumstances." },
      { term: "Right to be forgotten", text: "In some cases, you have the right to have us delete personal data about you that we no longer need for the purpose it was collected for." },
      { term: "Right to transfer your personal data (data portability)", text: "If we process your personal data to fulfill a contract or on the basis of your consent, you may, in certain cases, be able to obtain the personal data in a machine-readable format." },
      { term: "Right to withdraw consent", text: "In those cases where we process your personal data based on your consent, you have the right to withdraw your consent at any time." },
      { term: "Right to lodge a complaint", text: "If you have objections or concerns about how we process your personal data, you have the right to contact, or lodge a complaint with, the relevant authority for privacy protection." },
    ],
    afterContent: `To exercise your rights, please contact us at any time. We reserve the right to limit our facilitating such requests to that which is required by applicable law.\n\nIn order to protect your personal data from unauthorized access or deletion, we may require you to verify your identity before we will process any request to know or delete personal data.`,
  },
  {
    num: "7",
    title: "How do we keep your personal data safe",
    content: `We take significant and appropriate steps to protect your personal data in an effort to prevent loss, misuse, and unauthorized access, disclosure, alteration and destruction. We use appropriate technical and organizational measures to protect your personal information which may include: physical access controls, encryption, intrusion detection and network monitoring depending on the nature of the information and the scope of processing.\n\nFor more information regarding our security measures, please view our Security Policy.`,
  },
  {
    num: "8",
    title: "How long do we store your personal data",
    content: `Legora retains your personal information for as long as necessary to fulfill the purposes for which we collected it or longer if that is required under applicable law:`,
    list: [
      "If you are a Legora user covered by a Subscription Agreement between your employer and Legora, we will delete your data in accordance with that Subscription Agreement.",
      "Personal data that Legora is under a legal obligation to retain, for example under anti-money laundering or bookkeeping laws, is retained for the required periods under applicable laws (generally for 5 or 7 years).",
      "Personal data which is not used for the purposes of a contractual relationship or where Legora does not have a legal obligation to retain the data is only retained as long as necessary to fulfil the respective purpose for our data processing (usually 3 months).",
    ],
    afterContent: `More information can be found in the table in Section 3.\n\nWhen we no longer need your personal data, we will delete it or anonymize it in accordance with our data retention policies and applicable laws.`,
  },
  {
    num: "9",
    title: "Updates to this Privacy Policy",
    content: `We may update this Privacy Policy from time to time. When the Privacy Policy is updated, we will post an updated version on this page, unless another type of notice is required by applicable law or contractual agreement. By continuing to use our Online Services or providing us with personal data after we have posted an updated Privacy Policy, or notified you by other means, you consent to the revised Privacy Policy.`,
  },
  {
    num: "10",
    title: "Contact us",
    content: `If you have any questions about our Privacy Policy or any other privacy related issue, please contact us at privacy@legora.com or via mail.`,
    contactBlock: true,
  },
];

function renderBold(text) {
  const parts = text.split(/\*\*(.*?)\*\*/g);
  return parts.map((p, i) =>
    i % 2 === 1 ? <strong key={i} style={{ fontWeight: 600, color: "#111" }}>{p}</strong> : p
  );
}

function renderContent(text) {
  return text.split("\n\n").map((para, i) => (
    <p key={i} style={{ margin: "0 0 16px 0", color: "#444", fontSize: "15px", lineHeight: "1.75" }}>
      {renderBold(para)}
    </p>
  ));
}

function SectionBlock({ sec, active, onToggle }) {
  return (
    <div style={{ borderBottom: "1px solid #e8e8e8" }}>
      <button
        onClick={onToggle}
        style={{
          width: "100%", background: "none", border: "none", cursor: "pointer",
          display: "flex", alignItems: "center", gap: "0",
          padding: "0", textAlign: "left",
        }}
      >
        <div style={{
          width: "56px", minWidth: "56px",
          padding: "22px 0",
          display: "flex", alignItems: "center", justifyContent: "center",
          borderRight: "1px solid #e8e8e8",
        }}>
          <span style={{ fontSize: "13px", color: "#999", fontFamily: "inherit" }}>{sec.num}</span>
        </div>
        <div style={{
          flex: 1, padding: "22px 24px", display: "flex", alignItems: "center",
          justifyContent: "space-between",
        }}>
          <span style={{ fontSize: "15px", fontWeight: 500, color: "#111", fontFamily: "inherit" }}>
            {sec.title}
          </span>
          <span style={{
            fontSize: "20px", color: "#999", lineHeight: 1,
            transform: active ? "rotate(45deg)" : "none",
            transition: "transform 0.2s",
            marginLeft: "16px",
          }}>+</span>
        </div>
      </button>

      {active && (
        <div style={{ padding: "0 24px 28px 80px" }}>
          {sec.content && renderContent(sec.content)}

          {sec.list && (
            <ul style={{ paddingLeft: "20px", margin: "0 0 16px 0" }}>
              {sec.list.map((item, i) => (
                <li key={i} style={{ color: "#444", fontSize: "15px", lineHeight: "1.75", marginBottom: "6px" }}>{item}</li>
              ))}
            </ul>
          )}

          {sec.boldList && (
            <div style={{ marginTop: "4px" }}>
              {sec.boldList.map((item, i) => (
                <p key={i} style={{ color: "#444", fontSize: "15px", lineHeight: "1.75", marginBottom: "12px" }}>
                  <strong style={{ fontWeight: 600, color: "#111" }}>{item.term}</strong>
                  {": "}{item.text}
                </p>
              ))}
            </div>
          )}

          {sec.italicList && (
            <ul style={{ paddingLeft: "20px", margin: "0 0 16px 0" }}>
              {sec.italicList.map((item, i) => (
                <li key={i} style={{ color: "#444", fontSize: "15px", lineHeight: "1.75", marginBottom: "10px" }}>
                  <em style={{ fontStyle: "italic", color: "#111" }}>{item.term}</em>
                  {". "}{item.text}
                </li>
              ))}
            </ul>
          )}

          {sec.subsections && sec.subsections.map((sub, si) => (
            <div key={si} style={{ marginBottom: "24px" }}>
              <h5 style={{ fontSize: "14px", fontWeight: 600, color: "#111", margin: "0 0 12px 0", textTransform: "uppercase", letterSpacing: "0.05em" }}>
                {sub.num} — {sub.title}
              </h5>
              {renderContent(sub.content)}
              {sub.bullets && (
                <ul style={{ paddingLeft: "20px", margin: "0 0 8px 0" }}>
                  {sub.bullets.map((b, bi) => (
                    <li key={bi} style={{ color: "#444", fontSize: "15px", lineHeight: "1.75", marginBottom: "8px" }}>
                      <em style={{ fontStyle: "italic", color: "#111" }}>{b.label}</em>{": "}{b.text}
                    </li>
                  ))}
                </ul>
              )}
            </div>
          ))}

          {sec.tableNote && (
            <p style={{ color: "#444", fontSize: "15px", lineHeight: "1.75", margin: "16px 0 12px 0" }}>{sec.tableNote}</p>
          )}

          {sec.table && (
            <div style={{ overflowX: "auto", margin: "0 0 16px 0" }}>
              <table style={{ width: "100%", borderCollapse: "collapse", fontSize: "13.5px" }}>
                <thead>
                  <tr style={{ borderBottom: "2px solid #111" }}>
                    {["Purpose","Types of personal data","Legal basis","Data retention"].map(h => (
                      <th key={h} style={{ textAlign: "left", padding: "10px 12px", fontWeight: 600, color: "#111", whiteSpace: "nowrap" }}>{h}</th>
                    ))}
                  </tr>
                </thead>
                <tbody>
                  {sec.table.map((row, ri) => (
                    <tr key={ri} style={{ borderBottom: "1px solid #e8e8e8", verticalAlign: "top" }}>
                      <td style={{ padding: "12px", color: "#444", lineHeight: 1.6 }}>{row.purpose}</td>
                      <td style={{ padding: "12px", color: "#444", lineHeight: 1.6 }}>{row.data}</td>
                      <td style={{ padding: "12px", color: "#444", lineHeight: 1.6 }}>{row.basis}</td>
                      <td style={{ padding: "12px", color: "#444", lineHeight: 1.6 }}>{row.retention}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}

          {sec.afterContent && renderContent(sec.afterContent)}

          {sec.contactBlock && (
            <div style={{ marginTop: "8px" }}>
              <p style={{ fontWeight: 600, color: "#111", fontSize: "15px", margin: "0 0 6px 0" }}>Controller's Contact Information:</p>
              <p style={{ color: "#444", fontSize: "15px", lineHeight: "1.75", margin: 0 }}>
                Legora AB, 559338-6872<br />
                Box 7242<br />
                103 89 Stockholm<br />
                Sweden<br />
                <a href="mailto:privacy@legora.com" style={{ color: "#111", fontWeight: 500 }}>privacy@legora.com</a>
              </p>
            </div>
          )}
        </div>
      )}
    </div>
  );
}

export default function LegoraPrivacyPolicy() {
  const [activeSection, setActiveSection] = useState(null);

  const toggle = (num) => setActiveSection(a => a === num ? null : num);

  return (
    <div style={{ fontFamily: "'Inter', -apple-system, BlinkMacSystemFont, sans-serif", background: "#fff", color: "#111", minHeight: "100vh" }}>

      <Navbar />

      {/* Hero Section */}
      <div style={{ borderBottom: "1px solid #e8e8e8" }}>
        <div style={{ maxWidth: "1200px", margin: "0 auto", padding: "0 48px" }}>
          <div style={{ padding: "48px 0 40px" }}>
           
          </div>
          <h1 style={{
            fontSize: "clamp(56px, 8vw, 96px)",
            fontWeight: 700,
            color: "#111",
            margin: "0 0 80px 0",
            letterSpacing: "-0.03em",
            lineHeight: 1,
          }}>
            Privacy Policy
          </h1>
        </div>
      </div>

      {/* Content */}
      <div style={{ maxWidth: "1200px", margin: "0 auto", padding: "0 48px" }}>
        <main style={{ maxWidth: "780px", marginLeft: "auto", paddingTop: "56px", paddingBottom: "80px" }}>
          <p style={{ fontSize: "13px", color: "#999", margin: "0 0 28px 0" }}>Last updated February 28, 2025</p>

          <p style={{ fontSize: "15px", color: "#444", lineHeight: "1.75", margin: "0 0 14px 0" }}>
            Legora respects your privacy and is committed to securing and protecting any information we have about you. This policy (the <strong style={{ color: "#111" }}>"Privacy Policy"</strong>) covers our treatment of personal data about you whenever you access or use Legora products, services, features and technologies, including Legora's website (the <strong style={{ color: "#111" }}>"Site"</strong>), platform and plug-ins exchanging information with Legora (<strong style={{ color: "#111" }}>"Services"</strong>). The Privacy Policy also covers other interactions you have with Legora and describes your rights and how you can exercise them. The Site and Services are collectively referred to as <strong style={{ color: "#111" }}>"Online Services"</strong>.
          </p>
          <p style={{ fontSize: "15px", color: "#444", lineHeight: "1.75", margin: "0 0 40px 0" }}>
            You accept this Privacy Policy by using the Online Services. If you have any questions or concerns about the Privacy Policy, please{" "}
            <a href="#" style={{ color: "#111", textDecoration: "underline" }}>contact us</a>.
          </p>

          <div style={{ border: "1px solid #e8e8e8", borderRadius: "12px", overflow: "hidden" }}>
            {SECTIONS.map((sec) => (
              <SectionBlock
                key={sec.num}
                sec={sec}
                active={activeSection === sec.num}
                onToggle={() => toggle(sec.num)}
              />
            ))}
          </div>
        </main>
      </div>

      <Footer />

    </div>
  );
}